version: '3.8'
services:
  dev-db:
    build: ./mongodb_replica
    image: mongo
    container_name: "mongo"
    ports:
      # - "5434:5432"
      - "27018:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_REPLICA_HOST: host.docker.internal
      MONGO_REPLICA_PORT: 27018
    # networks:
    #   - mohoss
  # test-db:
  #   image: postgres:13
  #   ports:
  #     - "5435:5432"
  #   environment:
  #     POSTGRES_USER: dev
  #     POSTGRES_PASSWORD: 123
  #     POSTGRES_DB: nest
  #   networks:
  #     - mohoss
# networks:
#   mohoss: